<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RacesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('races')->insert([
            ['label' => 'Croisé', 'id_type_fk' => 1],
            ['label' => 'Terrier', 'id_type_fk' => 1],
            ['label' => 'Akita Inu', 'id_type_fk' => 1],
            ['label' => 'Bulldog', 'id_type_fk' => 1],
            ['label' => 'Husky', 'id_type_fk' => 1],
            ['label' => 'Pit Bull', 'id_type_fk' => 1],
            ['label' => 'Pit Bull Terrier', 'id_type_fk' => 1],
            ['label' => 'Staffordshire', 'id_type_fk' => 1],
            ['label' => 'Danois', 'id_type_fk' => 1],
            ['label' => 'Bangkaew de Thaïlande', 'id_type_fk' => 1],
            ['label' => 'Barbet', 'id_type_fk' => 1],
            ['label' => 'Basset', 'id_type_fk' => 1],
            ['label' => 'Basset Fauve de Bretagne', 'id_type_fk' => 1],
            ['label' => 'Basset Hound', 'id_type_fk' => 1],
            ['label' => 'Basset artésien normand', 'id_type_fk' => 1],
            ['label' => 'Basset bleu de Gascogne', 'id_type_fk' => 1],
            ['label' => 'Basset de Westphalie', 'id_type_fk' => 1],
            ['label' => 'Basset des Alpes', 'id_type_fk' => 1],
            ['label' => 'Basset suédois', 'id_type_fk' => 1],
            ['label' => 'Beagle', 'id_type_fk' => 1],
            ['label' => 'Bearded Collie', 'id_type_fk' => 1],
            ['label' => 'Beauceron', 'id_type_fk' => 1],
            ['label' => 'Berger Blanc suisse', 'id_type_fk' => 1],
            ['label' => 'Berger Picard', 'id_type_fk' => 1],
            ['label' => 'Berger allemand', 'id_type_fk' => 1],
            ['label' => 'Berger australien', 'id_type_fk' => 1],
            ['label' => 'Berger basque', 'id_type_fk' => 1],
            ['label' => 'Berger belge', 'id_type_fk' => 1],
            ['label' => 'Berger bulgare', 'id_type_fk' => 1],
            ['label' => 'Berger croate', 'id_type_fk' => 1],
            ['label' => 'Berger des Pyrénées', 'id_type_fk' => 1],
            ['label' => 'Berger finnois de Laponie', 'id_type_fk' => 1],
            ['label' => 'Berger hollandais', 'id_type_fk' => 1],
            ['label' => 'Berger polonais', 'id_type_fk' => 1],
            ['label' => 'Bichon Frisé', 'id_type_fk' => 1],
            ['label' => 'Bichon maltais', 'id_type_fk' => 1],
            ['label' => 'Border Collie', 'id_type_fk' => 1],
            ['label' => 'Border Terrier', 'id_type_fk' => 1],
            ['label' => 'Boston Terrier', 'id_type_fk' => 1],
            ['label' => 'Bouledogue', 'id_type_fk' => 1],
            ['label' => 'Bouledogue américain', 'id_type_fk' => 1],
            ['label' => 'Bouledogue anglais', 'id_type_fk' => 1],
            ['label' => 'Bouledogue français', 'id_type_fk' => 1],
            ['label' => 'Bouvier australien', 'id_type_fk' => 1],
            ['label' => 'Bouvier bernois', 'id_type_fk' => 1],
            ['label' => 'Bouvier des Flandres', 'id_type_fk' => 1],
            ['label' => 'Boxer', 'id_type_fk' => 1],
            ['label' => 'Brachet', 'id_type_fk' => 1],
            ['label' => 'Braque', 'id_type_fk' => 1],
            ['label' => 'Braque Saint-Germain', 'id_type_fk' => 1],
            ['label' => 'Braque allemand', 'id_type_fk' => 1],
            ['label' => 'Braque francais', 'id_type_fk' => 1],
            ['label' => 'Braque hongrois', 'id_type_fk' => 1],
            ['label' => 'Braque italien', 'id_type_fk' => 1],
            ['label' => 'Braque slovaque', 'id_type_fk' => 1],
            ['label' => 'Bull Terrier', 'id_type_fk' => 1],
            ['label' => 'Bullmastiff', 'id_type_fk' => 1],
            ['label' => 'Cairn Terrier', 'id_type_fk' => 1],
            ['label' => 'Cane Corso Italiano', 'id_type_fk' => 1],
            ['label' => 'Caniche', 'id_type_fk' => 1],
            ['label' => 'Carlin', 'id_type_fk' => 1],
            ['label' => 'Cavalier King Charles', 'id_type_fk' => 1],
            ['label' => 'Chien courant', 'id_type_fk' => 1],
            ['label' => 'Chien d\'arrêt', 'id_type_fk' => 1],
            ['label' => 'Chien d\'eau', 'id_type_fk' => 1],
            ['label' => 'Chien de Canaan', 'id_type_fk' => 1],
            ['label' => 'Chien de Caroline', 'id_type_fk' => 1],
            ['label' => 'Chien de Montagne des Pyrénées', 'id_type_fk' => 1],
            ['label' => 'Chien de berger', 'id_type_fk' => 1],
            ['label' => 'Chien de garenne', 'id_type_fk' => 1],
            ['label' => 'Chien du Groenland', 'id_type_fk' => 1],
            ['label' => 'Chien finnois de Laponie', 'id_type_fk' => 1],
            ['label' => 'Chien-loup', 'id_type_fk' => 1],
            ['label' => 'Chien-loup', 'id_type_fk' => 1],
            ['label' => 'Chihuahua', 'id_type_fk' => 1],
            ['label' => 'Chinook', 'id_type_fk' => 1],
            ['label' => 'Chow-Chow', 'id_type_fk' => 1],
            ['label' => 'Spaniel', 'id_type_fk' => 1],
            ['label' => 'Cocker', 'id_type_fk' => 1],
            ['label' => 'Colley', 'id_type_fk' => 1],
            ['label' => 'Dalmatien', 'id_type_fk' => 1],
            ['label' => 'Dandie Dinmont Terrier', 'id_type_fk' => 1],
            ['label' => 'Dobermann', 'id_type_fk' => 1],
            ['label' => 'Dogue Argentin', 'id_type_fk' => 1],
            ['label' => 'Dogue allemand', 'id_type_fk' => 1],
            ['label' => 'Dogue de Bordeaux', 'id_type_fk' => 1],
            ['label' => 'Dogue de Majorque', 'id_type_fk' => 1],
            ['label' => 'Dogue des Canaries', 'id_type_fk' => 1],
            ['label' => 'Dogue du Tibet', 'id_type_fk' => 1],
            ['label' => 'Epagneul', 'id_type_fk' => 1],
            ['label' => 'Epagneul Breton', 'id_type_fk' => 1],
            ['label' => 'Epagneul français', 'id_type_fk' => 1],
            ['label' => 'Eurasier', 'id_type_fk' => 1],
            ['label' => 'Fox-Terrier', 'id_type_fk' => 1],
            ['label' => 'Foxhound américain', 'id_type_fk' => 1],
            ['label' => 'Foxhound anglais', 'id_type_fk' => 1],
            ['label' => 'Golden Retriever', 'id_type_fk' => 1],
            ['label' => 'Grand Basset', 'id_type_fk' => 1],
            ['label' => 'Grand bouvier', 'id_type_fk' => 1],
            ['label' => 'Hokkaido', 'id_type_fk' => 1],
            ['label' => 'Huntaway', 'id_type_fk' => 1],
            ['label' => 'Husky de Sibérie', 'id_type_fk' => 1],
            ['label' => 'Jack Russell Terrier', 'id_type_fk' => 1],
            ['label' => 'Jindo Coréen', 'id_type_fk' => 1],
            ['label' => 'Khortaï', 'id_type_fk' => 1],
            ['label' => 'Kintamani', 'id_type_fk' => 1],
            ['label' => 'Kishu Inu', 'id_type_fk' => 1],
            ['label' => 'Labradoodle', 'id_type_fk' => 1],
            ['label' => 'Labrador Retriever', 'id_type_fk' => 1],
            ['label' => 'Lakeland Terrier', 'id_type_fk' => 1],
            ['label' => 'Lancashire Heeler', 'id_type_fk' => 1],
            ['label' => 'Laïka', 'id_type_fk' => 1],
            ['label' => 'Lhassa', 'id_type_fk' => 1],
            ['label' => 'Lurcher', 'id_type_fk' => 1],
            ['label' => 'Lévrier', 'id_type_fk' => 1],
            ['label' => 'Lévrier afghan', 'id_type_fk' => 1],
            ['label' => 'Lévrier anglais', 'id_type_fk' => 1],
            ['label' => 'Lévrier espagnol', 'id_type_fk' => 1],
            ['label' => 'Malamute d\'Alaska', 'id_type_fk' => 1],
            ['label' => 'Malinois', 'id_type_fk' => 1],
            ['label' => 'Manchester Terrier', 'id_type_fk' => 1],
            ['label' => 'Mastiff', 'id_type_fk' => 1],
            ['label' => 'Norfolk Terrier', 'id_type_fk' => 1],
            ['label' => 'Norwich Terrier', 'id_type_fk' => 1],
            ['label' => 'Petit Basset', 'id_type_fk' => 1],
            ['label' => 'Petit lévrier', 'id_type_fk' => 1],
            ['label' => 'Petit épagneul', 'id_type_fk' => 1],
            ['label' => 'Pinscher', 'id_type_fk' => 1],
            ['label' => 'Plott Hound', 'id_type_fk' => 1],
            ['label' => 'Plummer Terrier', 'id_type_fk' => 1],
            ['label' => 'Pékinois', 'id_type_fk' => 1],
            ['label' => 'Rat Terrier', 'id_type_fk' => 1],
            ['label' => 'Ratier', 'id_type_fk' => 1],
            ['label' => 'Retriever', 'id_type_fk' => 1],
            ['label' => 'Rottweiler', 'id_type_fk' => 1],
            ['label' => 'Saint-Bernard', 'id_type_fk' => 1],
            ['label' => 'Samoyède', 'id_type_fk' => 1],
            ['label' => 'Schnauzer', 'id_type_fk' => 1],
            ['label' => 'Setter Gordon', 'id_type_fk' => 1],
            ['label' => 'Setter anglais', 'id_type_fk' => 1],
            ['label' => 'Setter irlandais', 'id_type_fk' => 1],
            ['label' => 'Shar-Pei', 'id_type_fk' => 1],
            ['label' => 'Shetland', 'id_type_fk' => 1],
            ['label' => 'Shiba Inu', 'id_type_fk' => 1],
            ['label' => 'Shih-Tzu', 'id_type_fk' => 1],
            ['label' => 'Spinone', 'id_type_fk' => 1],
            ['label' => 'Spitz Japonais', 'id_type_fk' => 1],
            ['label' => 'Spitz allemand', 'id_type_fk' => 1],
            ['label' => 'Spitz finlandais', 'id_type_fk' => 1],
            ['label' => 'Springer anglais', 'id_type_fk' => 1],
            ['label' => 'Sussex Spaniel', 'id_type_fk' => 1],
            ['label' => 'Teckel', 'id_type_fk' => 1],
            ['label' => 'Terre-Neuve', 'id_type_fk' => 1],
            ['label' => 'Toy Fox Terrier', 'id_type_fk' => 1],
            ['label' => 'Corgi', 'id_type_fk' => 1],
            ['label' => 'West Highland White Terrier', 'id_type_fk' => 1],
            ['label' => 'Whippet', 'id_type_fk' => 1],
            ['label' => 'Yorkshire Terrier', 'id_type_fk' => 1],
            ['label' => 'Épagneul King Charles', 'id_type_fk' => 1],
            ['label' => 'Abyssin', 'id_type_fk' => 2],
            ['label' => 'American curl', 'id_type_fk' => 2],
            ['label' => 'American shorthair', 'id_type_fk' => 2],
            ['label' => 'American wirehair', 'id_type_fk' => 2],
            ['label' => 'Anatoli', 'id_type_fk' => 2],
            ['label' => 'Angora turc', 'id_type_fk' => 2],
            ['label' => 'Asian', 'id_type_fk' => 2],
            ['label' => 'Australian mist', 'id_type_fk' => 2],
            ['label' => 'Balinais', 'id_type_fk' => 2],
            ['label' => 'Bengal', 'id_type_fk' => 2],
            ['label' => 'Bleu russe', 'id_type_fk' => 2],
            ['label' => 'Bobtail américain', 'id_type_fk' => 2],
            ['label' => 'Bobtail japonais', 'id_type_fk' => 2],
            ['label' => 'Bombay', 'id_type_fk' => 2],
            ['label' => 'Brazilian shorthair', 'id_type_fk' => 2],
            ['label' => 'British longhair', 'id_type_fk' => 2],
            ['label' => 'British shorthair', 'id_type_fk' => 2],
            ['label' => 'Burmese americain', 'id_type_fk' => 2],
            ['label' => 'Burmese anglais', 'id_type_fk' => 2],
            ['label' => 'Burmilla', 'id_type_fk' => 2],
            ['label' => 'Californian Spangled', 'id_type_fk' => 2],
            ['label' => 'Californian rex', 'id_type_fk' => 2],
            ['label' => 'Celtic Shorthair (European Shortair)', 'id_type_fk' => 2],
            ['label' => 'Ceylan', 'id_type_fk' => 2],
            ['label' => 'Chantilly', 'id_type_fk' => 2],
            ['label' => 'Chartreux', 'id_type_fk' => 2],
            ['label' => 'Chat de gouttière', 'id_type_fk' => 2],
            ['label' => 'Chat européen', 'id_type_fk' => 2],
            ['label' => 'Chausie', 'id_type_fk' => 2],
            ['label' => 'Colorpoint shorthair', 'id_type_fk' => 2],
            ['label' => 'Colourpoint', 'id_type_fk' => 2],
            ['label' => 'Cornish rex', 'id_type_fk' => 2],
            ['label' => 'Cymric', 'id_type_fk' => 2],
            ['label' => 'Devon rex', 'id_type_fk' => 2],
            ['label' => 'Donskoy', 'id_type_fk' => 2],
            ['label' => 'Exotic shorthair', 'id_type_fk' => 2],
            ['label' => 'German rex', 'id_type_fk' => 2],
            ['label' => 'Havana brown', 'id_type_fk' => 2],
            ['label' => 'Highland Fold (Scottish Fold)', 'id_type_fk' => 2],
            ['label' => 'Highlander', 'id_type_fk' => 2],
            ['label' => 'Himalayen', 'id_type_fk' => 2],
            ['label' => 'Khao manee', 'id_type_fk' => 2],
            ['label' => 'Korat', 'id_type_fk' => 2],
            ['label' => 'Kurilian bobtail', 'id_type_fk' => 2],
            ['label' => 'LaPerm', 'id_type_fk' => 2],
            ['label' => 'Maine coon', 'id_type_fk' => 2],
            ['label' => 'Mandarin', 'id_type_fk' => 2],
            ['label' => 'Manx', 'id_type_fk' => 2],
            ['label' => 'Mau arabe', 'id_type_fk' => 2],
            ['label' => 'Mau Égyptien', 'id_type_fk' => 2],
            ['label' => 'Minskin', 'id_type_fk' => 2],
            ['label' => 'Munchkin', 'id_type_fk' => 2],
            ['label' => 'Nebelung', 'id_type_fk' => 2],
            ['label' => 'Norvégien', 'id_type_fk' => 2],
            ['label' => 'Ocicat', 'id_type_fk' => 2],
            ['label' => 'Ojos azules', 'id_type_fk' => 2],
            ['label' => 'Oriental', 'id_type_fk' => 2],
            ['label' => 'Persan', 'id_type_fk' => 2],
            ['label' => 'Peterbald', 'id_type_fk' => 2],
            ['label' => 'Pixie-bob', 'id_type_fk' => 2],
            ['label' => 'Ragamuffin', 'id_type_fk' => 2],
            ['label' => 'Ragdoll', 'id_type_fk' => 2],
            ['label' => 'Sacré de Birmanie', 'id_type_fk' => 2],
            ['label' => 'Safari', 'id_type_fk' => 2],
            ['label' => 'Savannah', 'id_type_fk' => 2],
            ['label' => 'Scottish fold', 'id_type_fk' => 2],
            ['label' => 'Selkirk rex', 'id_type_fk' => 2],
            ['label' => 'Serengeti', 'id_type_fk' => 2],
            ['label' => 'Seychellois', 'id_type_fk' => 2],
            ['label' => 'Siamois', 'id_type_fk' => 2],
            ['label' => 'Sibérien', 'id_type_fk' => 2],
            ['label' => 'Singapura', 'id_type_fk' => 2],
            ['label' => 'Skookum', 'id_type_fk' => 2],
            ['label' => 'Snowshoe', 'id_type_fk' => 2],
            ['label' => 'Sokoké', 'id_type_fk' => 2],
            ['label' => 'Somali', 'id_type_fk' => 2],
            ['label' => 'Sphynx', 'id_type_fk' => 2],
            ['label' => 'Thai', 'id_type_fk' => 2],
            ['label' => 'Tonkinois', 'id_type_fk' => 2],
            ['label' => 'Toyger', 'id_type_fk' => 2],
            ['label' => 'Turc de van', 'id_type_fk' => 2],
            ['label' => 'Ural rex', 'id_type_fk' => 2],
            ['label' => 'York chocolat', 'id_type_fk' => 2],
            ['label' => 'Oiseau', 'id_type_fk' => 3],
            ['label' => 'Reptile', 'id_type_fk' => 3],
            ['label' => 'Rongeur', 'id_type_fk' => 3],
            ['label' => 'Carnivores', 'id_type_fk' => 3]
        ]);
    }
}
